# Generated by Django 5.2.4 on 2025-07-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_is_default_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title_ar',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_en',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
