# Generated by Django 5.2.4 on 2025-07-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_title_ar_alter_card_title_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hour_range_start', models.TimeField()),
                ('hour_range_end', models.TimeField()),
                ('click_count', models.PositiveIntegerField(help_text='Total number of clicks')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
