# Generated by Django 5.2.4 on 2025-07-15 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_interaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('user', 'card', 'hour_range_start'), name='unique_user_card_hour'),
        ),
    ]
