# Generated by Django 5.2.4 on 2025-07-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_category_image'),
        ('cards', '0005_interaction_unique_user_card_hour'),
    ]

    operations = [
    ]
