# Generated by Django 5.2.4 on 2025-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_premium_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscription_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
